### ISSUE TITLE
Add Wiki with proper user manual / documentation

### ISSUE THREAD

**Issue by curcuz** [resin-io-projects/boombeastic#11]
right now the README has the bare minimum info - it would be really nice to have a detailed guide that covers:
* assembly
* installation
* configuration
* general explanation of how it works

**Comment by sonyagreen** [comment]
@curcuz I went back through to clean up the outstanding comments. If this doesn't get touched by me or @mccollam in a few days, ship the PR and we can polish it more later.

**Comment by curcuz** [comment]
@sonyagreen I moved it as a wiki, thanks a lot for the contribution!
