### ISSUE TITLE
Docs: variable values are mis-identified

### ISSUE THREAD

**Issue by sonyagreen** [resin-io-projects/boombeastic#29]
*Creating an issue because it's a wiki and I'd like to make sure I understand this correctly before changing the wiki.*

Some configuration files ([example](https://github.com/resin-io-projects/boombeastic/wiki/Configuration)) have variable (eg. MOPIDY_SPOTIFY_USERNAME) with values that should be data the user provides (eg. username). Currently the value is set to `none` with the description stating the value. I found that confusing.

Suggestion for all username, password, and token fields: change values to (in this example) `username` and use the description to clarify that you should add *your* username, not the word `username`.

**Comment by sonyagreen** [comment]
Ah, I just RTFM and found
>If you have an account for a service you want to use with your Boombeastic, set the "ENABLED" variable to true and put your account information in the "Value" field on the "Environment Variable" section of the dashboard. If you don't have an account for a particular service or don't want to use it, just skip that service's section.

I think the tables could still be more clear.

Relatedly, some values are `true` and some are `0`. It would be clearer to know if the value is what is default, or what you want to set it to if you want to enable the extension.

**Comment by curcuz** [comment]
@sonyagreen I addressed the issue in the latest wiki revision. Let me know if it makes more sense now and feel free to close if so. Thanks a lot!
